name: URL Validation

on:
  push:
    branches: [ main ]
    paths:
      - '**/*.md'
      - '**/*.html'
      - 'docs/**'
  pull_request:
    branches: [ main ]
    paths:
      - '**/*.md'
      - '**/*.html'
      - 'docs/**'
  workflow_dispatch:

jobs:
  validate-urls:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '16'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Validate URLs
      run: npm run validate-urls || echo "URL validation found issues"
    
    - name: Upload validation report
      uses: actions/upload-artifact@v4
      with:
        name: url-validation-report
        path: ./url-report/
        if-no-files-found: warn